---
# tasks file for consul
  - name: Install build tools
    yum:
      name: "{{ packages }}"

  - name: Setup consul user
    user:
      name: "{{ consul_user }}"
      shell: /bin/false
      create_home: false

  - name: Download consul binary
    get_url:
      url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip"
      dest: /tmp/consul_{{ consul_version }}_linux_amd64.zip
      mode: 0644
  
  - name: Unzip consul artifact
    unarchive:
      src: /tmp/consul_{{ consul_version }}_linux_amd64.zip
      dest: /tmp/
      remote_src: yes

  - name: Check consul binary exists
    stat: path=/tmp/consul
    register: consul_exists

  - name: Move consul to /usr/bin
    command: mv /tmp/consul /usr/bin/
    when: consul_exists.stat.exists
  
  # - name: Copy consul server.hcl to /opt/
  #   template:
  #     src: server.hcl.j2
  #     dest: "{{ server_conf_path }}{{ server_conf_name }}"
  #     owner: "{{ consul_user }}"
  #     group: "{{ consul_user }}"
  #     mode: 0600
  #   notify:
  #     restart consul
  
  # - name: Copy consul service to /etc/systemd/system
  #   template:
  #     src: consul_service.j2
  #     dest: "/etc/systemd/system/consul.service"
  #     owner: "{{ consul_user }}"
  #     group: "{{ consul_user }}"
  #     mode: 0600
  #   notify:
  #     systemd reload

  # - name: Start consul service and enable it
  #   systemd:
  #     state: started
  #     name: consul