---
# tasks file for consul

  - name: DEBUG
    debug:
      var: ansible_facts

  - name: Install build tools
    become: yes
    yum:
      name: "{{ packages }}"

  - name: Setup consul user
    become: yes
    user:
      name: "{{ consul_user }}"
      shell: /bin/false
      create_home: false

  - name: Download consul binary
    get_url:
      url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip"
      dest: /tmp/consul_{{ consul_version }}_linux_amd64.zip
      mode: 0644
  
  - name: Unzip consul artifact
    unarchive:
      src: /tmp/consul_{{ consul_version }}_linux_amd64.zip
      dest: /tmp/
      remote_src: yes

  - name: Check consul binary exists
    stat: path=/tmp/consul
   

  - name: Copy consul binary to bin dir
    become: yes
    copy:
      src: /tmp/consul
      dest: /usr/bin/
      owner: "{{ consul_user }}"
      group: "{{ consul_user }}"
      # Dont forget to change below to 0644
      mode: 0755
      remote_src: yes
    
  - name: create config directories for consul
    become: yes
    file:
      path: /etc/consul.d
      state: directory
      owner: "{{ consul_user }}"
      group: "{{ consul_user }}"
      mode: 0755

  - name: Create data dir for consul
    become: yes
    file:
      path: "{{ consul_data_dir }}"
      state: directory
      owner: "{{ consul_user }}"
      group: "{{ consul_user }}"

  - name: Copy consul server config
    become: yes
    template:
      src: server_config.j2
      dest: "/etc/consul.d/server_config.json"
      owner: "{{ consul_user }}"
      group: "{{ consul_user }}"
      mode: 0755
    notify:
      restart_consul
  
  - name: Copy consul service to /etc/systemd/system
    become: yes
    template:
      src: consul_service.j2
      dest: "/etc/systemd/system/consul.service"
      owner: "{{ consul_user }}"
      group: "{{ consul_user }}"
    notify:
      systemd_reload

  - name: Start consul service and enable it
    become: yes
    systemd:
      name: consul
      state: started
      enabled: yes