scrape_configs:
# Scrape Prometheus itself every 2 seconds.
- job_name: 'prometheus'
  scrape_interval: 2s
  static_configs:
      - targets: ['localhost:9090']

- job_name: 'testVM'
  scrape_interval: 2s
  static_configs:
      - targets: ['192.168.1.200:9100']