---
# defaults file for filebeat
filebeat_version: 6.5.4
filebeat_create_config: true

filebeat_prospectors:
  - input_type: log
    paths:
      - "/var/log/*.log"

  - input_type: log
    paths:
      - "/var/log/messages"
    fields:
      syslog: true
    
  - input_type: log
    paths:
      - "/tmp/server1/alloc/logs/*"
    fields:
      nomad_dc: true
    
filebeat_output_elasticsearch_enabled: false
filebeat_output_elasticsearch_hosts:
  - "192.168.1.18:9200"

filebeat_output_logstash_enabled: true  
filebeat_output_logstash_hosts:
  - "192.168.1.18:5000"

filebeat_enable_logging: false
filebeat_log_level: warning
filebeat_log_dir: /var/log/mybeat
filebeat_log_filename: mybeat.log

filebeat_ssl_dir: /etc/pki/logstash
filebeat_ssl_certificate_file: ""
filebeat_ssl_key_file: ""
filebeat_ssl_insecure: "true"


dashboard_setup: "true" 

kibana_host: "192.168.1.18:5601"
kibana_protocol: "http"

f_modules:
  - apache