---
# tasks file for blackbox_exporter
- name: Setup blackbox user
  user:
    name: "{{ blackbox_user }}"
    shell: /bin/false
    create_home: false

- name: Download the blackbox binary
  get_url:
    url: https://github.com/prometheus/blackbox_exporter/releases/download/v{{ blackbox_version }}/blackbox_exporter-{{ blackbox_version }}.linux-amd64.tar.gz
    dest: /tmp/blackbox_exporter-{{ blackbox_version }}.linux-amd64.tar.gz
    mode: 0644    

- name: Untar the blackbox artifact
  unarchive:
    src: /tmp/blackbox_exporter-{{ blackbox_version }}.linux-amd64.tar.gz
    dest: /tmp/
    owner: "{{ blackbox_user }}"
    mode: 0644

- name: Move blackbox exporter binary
  command: mv /tmp/blackbox_exporter-{{ blackbox_version }}.linux-amd64/blackbox_exporter /usr/local/bin/blackbox_exporter

- name: Own the binary to user
  file:
    path: /usr/local/bin/blackbox_exporter
    owner: "{{ blackbox_user }}"

   