---
# handlers file for consul
-   name: systemd_reload
    become: yes
    systemd:
        name: consul
        state: restarted
        daemon_reload: yes

-   name: restart_consul
    become: yes
    systemd:
        name: consul
        state: restarted
